### ISSUE TITLE
Multi resolution resource management

### ISSUE THREAD

**Issue by dmalves** [b3dgs/lionengine#285]
Hi, nice engine.

How do you handle multiple screen sizes, specially on android devices? 

thx

**Comment by DjThunder** [comment]
Hi,

You have the _Native_ resolution (defined in the Sequence), also named as _Source_ resolution in your _Config_. And the _Output_ resolution, which represents the expected target resolution.

320*240 as source, and 640*480 as target will perform a scale x2. It works like this on a computer.

But on Android, this is different. It is better to use the same resolution for both _Source_ and _Output_, as the rendering will fill the device screen. Scaled will be performed directly by the device on the fly, not by the engine.

If you design a game to run in 240*400, then it will run fine on any devices with this ratio (480*800...).
Of course, if your rotate your screen to _Horizontal_  (400*240, 800*480...), rendering may not be correctly adapted, as it will stretch to fit screen, looking like crushed.

But if you implement this in your app (you have a callback _onResolutionChanged_ in your _Sequence_), you can adapt rendering to fit correctly in many situation.

**Comment by dmalves** [comment]
Thanks for replying,

my main concern is not letting Android scale everything by itself. I mean, usually an Android game comes with image assets for different resolutions and aspect ratios. Everything goes on assets sub-directories, so Android could select the best match for the device resolution. 

So, how is it done on lionengine? How do I select different assets for the same sprites? I am not worried about screen rotation, as I could fix the screen orientation to landscape (Manifest  file if I remember it right) and forget about it.

On Mario Bros tutorial was not clear where I should place the resources in case I use Android api. And it was not clear how to handle multiple resolutions and  in case of Android games, I must say, knowing how to handle multiple screen sizes is a must have. Could you please instruct me on this matter? It would be nice some directions on the Tutorial itself, so others could make good use of it too.

LIONENGINE appeared when I was looking for an engine that used Android CANVAS. I think that Android Canvas is good enough for retro games. And makes things a little easier. I am surprised to see it has its own map editor. Usually people use something like TILED (www.mapeditor.org/).

What makes this engine unique is that it is java only. Most engines are a mix of java,c,c++ and the list goes on, making the code difficult to understand as a lot of code experience may be required. You have a nice code there. Pretty clean and easy to understand.

**Comment by DjThunder** [comment]
Yes, I can see that something is missing.
I will try to make this clear for the next release (Maybe end of this month).
I will also update the LionEngine website for a dedicated Android tutorial, as it is a little bit more specific compared to AWT or SWT.

Thanks a lot for the feedback.

_(Note: Maybe one day I will try to provide an import / export to make it compatible with TILED, as it is a classic)._

**Comment by DjThunder** [comment]
An example can be found here : https://github.com/b3dgs/lionengine/tree/master/lionengine-examples/src/main/java/com/b3dgs/lionengine/example/core/dpi
