### ISSUE TITLE
Logotype

### ISSUE THREAD

**Issue by nunojesus** [b3dgs/lionengine#489]
Hi, How are you?
Im a graaphic designer that like to help projects in opensource for free, so if you like I can contribute with graphic designs,, I can make you a logotype for this project if you want, I like very much your project and the name is amazing!
So if you need some design just say it.

Greetings!
Nuno Jesus

**Comment by DjThunder** [comment]
Hello,

Why not :)
You can try with a design of your own.
Also, if you have some idea to redesign the website, feel free to enhance: https://lionengine.b3dgs.com/v8-4/page.php?lang=fr&section=home

**Comment by nunojesus** [comment]
Hello, I create some designs for your project, the concept is the same, but with minor variations, I also put different choices of text fonts.
At the end you will find my favorite logos, I hope you like one of them.

![lionengine](https://user-images.githubusercontent.com/34600369/41464924-ee8bf1b4-7093-11e8-9617-34aca2cb20d3.png)

**Comment by DjThunder** [comment]
Nice  !
Can you try with a less "neutral-classic" font ?

**Comment by nunojesus** [comment]
You want a modern one? do you want regular or bold?

Greetings

**Comment by nunojesus** [comment]
See if you like one of this fonts.

Greetings!

![lionengine2](https://user-images.githubusercontent.com/34600369/41486317-f20a465e-70db-11e8-9cf9-bafbdb2a7cb8.png)

**Comment by DjThunder** [comment]
Ah yes, i like the 3rd :)
Maybe a little bit less bright on the bottom section ? (a little little bit less)
What do you think about ?

**Comment by nunojesus** [comment]
I think it will look better, I will make the changes and post it here.

**Comment by nunojesus** [comment]
Is this what you want?
![lionengine3](https://user-images.githubusercontent.com/34600369/41490043-2be204ee-70ea-11e8-905e-3f2c52296251.png)

**Comment by DjThunder** [comment]
Yep nice!

**Comment by DjThunder** [comment]
PNG is enough for me :)

**Comment by DjThunder** [comment]
You can also replace the logo under the one you added on top (left to summary) using you logo with text at bottom.

**Comment by nunojesus** [comment]
I have found that the font used in the logo is for personal use only. So it would be better to switch to another free font for commercial use as well. What do you think? I'm so sorry for this. I'll try to find an even nicer font.

**Comment by nunojesus** [comment]
Se if you like one of this.

Greetings!

![text1](https://user-images.githubusercontent.com/34600369/41511463-e74a53f0-726e-11e8-96df-0132b9262c69.png)

**Comment by DjThunder** [comment]
The 1st is looking like the previous one ;)

**Comment by nunojesus** [comment]
i will put this with the logo, to see if it looks nice.

**Comment by nunojesus** [comment]
Hello, I change the logos with the new font and uploaded the new logos in the readme file (I put the 2 logos one on the top and the other in the summary box as you requested)

Greetings!

**Comment by DjThunder** [comment]
Cool !
