### ISSUE TITLE
Push newest Android core to maven

### ISSUE THREAD

**Issue by stoffel2107** [b3dgs/lionengine#521]
**Is your feature request related to a problem? Please describe.**
I wanted to use the android core to build my android app with LionEngine Core 9.0.0 but while compiling the newest android core(8.4.1) tries to find the engine in *.core.Engine instead of *.Engine where the newest core defines it.

**Describe the solution you'd like**
Push the android 9.0.0 to the maven repository

**Describe alternatives you've considered**
Building the Android core myself and deploy it to a private maven repository

**Additional context**
![image](https://user-images.githubusercontent.com/32580372/53630064-7cf33380-3c0f-11e9-82e2-3730866a5eba.png)

**Comment by DjThunder** [comment]
Pushed to https://oss.sonatype.org/content/groups/public/com/b3dgs/lionengine/lionengine-core-android/9.0.0/
